version: '3'
services:
  target1:
    build: .
    ports:
      - '5000:80'
      - '6000:22'
    container_name: target1
  target2:
    build: .
    ports:
      - '5001:80'
      - '6001:22'
    container_name: target2 
