apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssh-ubuntu
  labels:
    app: ssh-ubuntu
spec:
  selector:
    matchLabels:
      app: ssh-ubuntu
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ssh-ubuntu
    spec:
      restartPolicy: Always
      containers:
      - name: ssh-ubuntu
        image: prskid1000/ssh-ubuntu
        imagePullPolicy: Never
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /status
        #     port: 5000
        #   initialDelaySeconds: 3
        #   periodSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: disk
          mountPath: /disk
          
      volumes:
      - name: disk
        hostPath:
          path: /disk

#NOTE: comment out `volumes` section for configmap and\or secret guide
      # volumes:
      # - name: secret-volume
      #   secret:
      #     secretName: mysecret
      # - name: config-volume
      #   configMap:
      #     name: example-config #name of our configmap object
