apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssh-ubuntu-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/apache/1"
        backend:
          service:
            name: ssh-ubuntu-scv-1-80
            port:
              number: 31001
      - pathType: Prefix
        path: "/node/1"
        backend:
          service:
            name: ssh-ubuntu-scv-1-3000
            port:
              number: 30457
      - pathType: Prefix
        path: "/apache/2"
        backend:
          service:
            name: ssh-ubuntu-scv-2-80
            port:
              number: 31481
      - pathType: Prefix
        path: "/node/2"
        backend:
          service:
            name: ssh-ubuntu-scv-2-3000
            port:
              number: 30901