apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssh-ubuntu-ingress
  annotations:
spec:
  rules:
    - host: ssh-ubuntu.com
      http:
        paths:
          - pathType: Prefix
            path: /nginx
            backend:
              service:
                name: ssh-ubuntu-80 
                port:
                  number: 80

          - pathType: Prefix
            path: /serve
            backend:
              service:
                name: ssh-ubuntu-3000 
                port:
                  number: 3000
