apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-node-ingress
spec:
  rules:
  - host: "express-node-1.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: express-node-scv-1
            port:
              number: 31431
  - host: "express-node-2.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: express-node-scv-2
            port:
              number: 32008